"use client";

import { useMemo, useState } from "react";
import { CL_DATA } from "@/lib/data/checklist";
import { useApp } from "@/lib/context/AppProvider";

const clTotal = CL_DATA.reduce((s, sec) => s + sec.items.length, 0);

export function ChecklistView() {
  const { showToast } = useApp();
  const [checked, setChecked] = useState<Record<string, boolean>>({});

  const doneCount = useMemo(
    () => Object.values(checked).filter(Boolean).length,
    [checked]
  );
  const pct = Math.round((doneCount / clTotal) * 100);

  const toggleCL = (key: string) => {
    setChecked((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  const resetChecklist = () => {
    setChecked({});
    showToast("Checklist reset.");
  };

  const exportChecklist = () => {
    let out = "RENTER RIGHTS AI — MOVE-IN CHECKLIST\n";
    out +=
      "Exported: " +
      new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      }) +
      "\n";
    out += "─".repeat(48) + "\n\n";
    CL_DATA.forEach((sec, si) => {
      out += sec.sec.toUpperCase() + "\n";
      sec.items.forEach((item, ii) => {
        const key = si + "-" + ii;
        const mark = checked[key] ? "[x]" : "[ ]";
        out += mark + " " + item.t;
        if (item.n) out += " (" + item.n + ")";
        out += "\n";
      });
      out += "\n";
    });
    out += "─".repeat(48) + "\n";
    out += doneCount + " of " + clTotal + " items checked\n";
    out += "Generated by renterrightsai.com";
    navigator.clipboard
      .writeText(out)
      .then(() => showToast("Checklist copied — paste into an email to your landlord."))
      .catch(() => showToast("Could not copy. Try again."));
  };

  return (
    <>
      <div className="page-header">
        <div className="page-eyebrow">Move-in checklist</div>
        <h1 className="page-title">Protect your deposit from day one</h1>
        <p className="page-sub">
          Walk through every room and check off items. Photograph anything already damaged and share this
          list with your landlord in writing.
        </p>
      </div>

      <div className="progress-wrap">
        <div className="progress-row">
          <span>Inspection progress</span>
          <span id="cl-pct">
            {doneCount} of {clTotal} items
          </span>
        </div>
        <div className="progress-track">
          <div className="progress-fill" id="cl-fill" style={{ width: pct + "%" }} />
        </div>
      </div>

      <div className="callout callout-green">
        <svg viewBox="0 0 24 24">
          <polyline points="20 6 9 17 4 12" />
        </svg>
        <div>
          Tip: Email this completed checklist to your landlord on move-in day. This creates a timestamped
          record that protects you from being charged for pre-existing damage.
        </div>
      </div>

      <div id="cl-sections">
        {CL_DATA.map((sec, si) => (
          <div className="cl-section" key={sec.sec}>
            <div className="cl-section-title">
              <svg viewBox="0 0 24 24" dangerouslySetInnerHTML={{ __html: sec.icon }} />
              {sec.sec}
            </div>
            <div className="cl-items">
              {sec.items.map((item, ii) => {
                const key = si + "-" + ii;
                const done = !!checked[key];
                return (
                  <div
                    className={`cl-item${done ? " done" : ""}`}
                    id={`cl-${key}`}
                    key={key}
                    onClick={() => toggleCL(key)}
                    role="button"
                    tabIndex={0}
                  >
                    <div className="cl-checkbox" id={`cb-${key}`}>
                      <svg
                        className="cl-check-icon"
                        width="10"
                        height="10"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="#fff"
                        strokeWidth="3.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      >
                        <polyline points="20 6 9 17 4 12" />
                      </svg>
                    </div>
                    <div>
                      <div className="cl-text">{item.t}</div>
                      {item.n ? <div className="cl-note">{item.n}</div> : null}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      <div className="btn-row">
        <button className="btn btn-sm" type="button" onClick={exportChecklist}>
          <svg
            viewBox="0 0 24 24"
            width="15"
            height="15"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
            <polyline points="7 10 12 15 17 10" />
            <line x1="12" y1="15" x2="12" y2="3" />
          </svg>
          Export as text
        </button>
        <button className="btn btn-sm" type="button" onClick={resetChecklist}>
          Reset all
        </button>
      </div>
    </>
  );
}
