"use client";

import { useState } from "react";
import { TL_KEY, TL_TYPE_LABELS } from "@/lib/data/constants";
import { useLocalStorage } from "@/lib/hooks/useLocalStorage";
import { useApp } from "@/lib/context/AppProvider";
import { escHtml, formatLongDate, formatShortDate } from "@/lib/utils";
import type { TimelineEntry } from "@/types";

export function TimelineView() {
  const { isPro, openPaywall, showToast } = useApp();
  const [entries, setEntries] = useLocalStorage<TimelineEntry[]>(TL_KEY, []);
  const [date, setDate] = useState("");
  const [type, setType] = useState("report");
  const [note, setNote] = useState("");

  const sorted = [...entries].sort((a, b) => (a.date < b.date ? -1 : 1));

  const addTimelineEntry = () => {
    if (!isPro) {
      openPaywall(
        "Case timeline is a Pro feature",
        "Upgrade to Renter Rights Pro to log every event in your dispute with dates and notes — and export a court-ready record."
      );
      return;
    }
    if (!date) {
      showToast("Please select a date.");
      return;
    }
    setEntries((prev) => [
      ...prev,
      { id: Date.now(), date, type, note: note.trim() },
    ]);
    setNote("");
    setDate("");
    showToast("Event added to your timeline.");
  };

  const deleteTimelineEntry = (id: number) => {
    setEntries((prev) => prev.filter((e) => e.id !== id));
    showToast("Entry removed.");
  };

  const exportTimeline = () => {
    if (!entries.length) {
      showToast("No entries to export.");
      return;
    }
    let out = "RENTER RIGHTS AI — CASE TIMELINE\n";
    out +=
      "Exported: " +
      new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      }) +
      "\n";
    out += "─".repeat(48) + "\n\n";
    sorted.forEach((e) => {
      const label = TL_TYPE_LABELS[e.type as keyof typeof TL_TYPE_LABELS] || e.type;
      out += formatLongDate(e.date) + "\n";
      out += label + "\n";
      if (e.note) out += e.note + "\n";
      out += "\n";
    });
    out += "─".repeat(48) + "\n";
    out += "Generated by renterrightsai.com";
    navigator.clipboard
      .writeText(out)
      .then(() => showToast("Timeline copied — paste into a document or email."))
      .catch(() => showToast("Could not copy. Try again."));
  };

  const clearTimeline = () => {
    if (!confirm("Delete all timeline entries? This cannot be undone.")) return;
    setEntries([]);
    showToast("Timeline cleared.");
  };

  return (
    <>
      <div className="page-header">
        <div className="page-eyebrow">Case timeline</div>
        <h1 className="page-title">Your dispute log</h1>
        <p className="page-sub">
          Record every event in your dispute as it happens. Dates and notes create the evidence trail you
          need if things escalate to court or a housing authority complaint.
        </p>
      </div>

      <div className="callout callout-blue">
        <svg viewBox="0 0 24 24">
          <circle cx="12" cy="12" r="10" />
          <line x1="12" y1="8" x2="12" y2="12" />
          <line x1="12" y1="16" x2="12.01" y2="16" />
        </svg>
        <div>
          Your timeline is saved in this browser. To keep it permanently, use the Export button to copy it
          — then paste it into a document or email it to yourself.
        </div>
      </div>

      <div className="card" style={{ marginBottom: "1.5rem" }}>
        <div className="card-title">
          <svg
            viewBox="0 0 24 24"
            width="16"
            height="16"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <circle cx="12" cy="12" r="10" />
            <line x1="12" y1="8" x2="12" y2="12" />
            <line x1="12" y1="16" x2="12.01" y2="16" />
          </svg>
          Add an event
        </div>
        <div className="form-grid" style={{ marginBottom: 10 }}>
          <div className="form-group" style={{ marginBottom: 0 }}>
            <label className="form-label" htmlFor="tl-date">
              Date
            </label>
            <input
              className="form-input"
              id="tl-date"
              type="date"
              value={date}
              onChange={(e) => setDate(e.target.value)}
            />
          </div>
          <div className="form-group" style={{ marginBottom: 0 }}>
            <label className="form-label" htmlFor="tl-type">
              Event type
            </label>
            <select
              className="form-input"
              id="tl-type"
              value={type}
              onChange={(e) => setType(e.target.value)}
            >
              <option value="report">Reported issue to landlord</option>
              <option value="letter">Sent demand letter</option>
              <option value="response">Landlord responded</option>
              <option value="noresponse">Landlord did not respond</option>
              <option value="repair">Repair attempted</option>
              <option value="complaint">Filed housing complaint</option>
              <option value="inspection">Inspector visited</option>
              <option value="violation">Violation citation issued</option>
              <option value="court">Court hearing</option>
              <option value="payment">Payment made / received</option>
              <option value="other">Other</option>
            </select>
          </div>
        </div>
        <div className="form-group">
          <label className="form-label" htmlFor="tl-note">
            Notes{" "}
            <span
              style={{
                fontWeight: 400,
                textTransform: "none",
                letterSpacing: 0,
                color: "var(--text-3)",
              }}
            >
              (what happened, who was present, what was said)
            </span>
          </label>
          <textarea
            className="form-input"
            id="tl-note"
            rows={2}
            placeholder="e.g. Called landlord at 3pm. He said someone would come Thursday. No written confirmation given."
            style={{ resize: "vertical" }}
            value={note}
            onChange={(e) => setNote(e.target.value)}
          />
        </div>
        <div className="btn-row" style={{ marginTop: 0 }}>
          <button className="btn btn-primary" type="button" onClick={addTimelineEntry}>
            <svg
              viewBox="0 0 24 24"
              width="15"
              height="15"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <line x1="12" y1="5" x2="12" y2="19" />
              <line x1="5" y1="12" x2="19" y2="12" />
            </svg>
            Add to timeline
          </button>
        </div>
      </div>

      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 10,
          flexWrap: "wrap",
          gap: 8,
        }}
      >
        <div className="sec-label" style={{ marginBottom: 0 }} id="tl-count">
          {entries.length === 0
            ? "No entries yet"
            : `${entries.length} event${entries.length === 1 ? "" : "s"} logged`}
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          <button className="btn btn-sm" type="button" onClick={exportTimeline}>
            Export
          </button>
          <button
            className="btn btn-sm"
            type="button"
            onClick={clearTimeline}
            style={{ color: "var(--red)" }}
          >
            Clear all
          </button>
        </div>
      </div>

      <div id="tl-entries">
        {sorted.map((e) => {
          const label = TL_TYPE_LABELS[e.type as keyof typeof TL_TYPE_LABELS] || e.type;
          return (
            <div className="tl-entry" key={e.id}>
              <div className="tl-left">
                <div className={`tl-dot tl-dot-${e.type}`} />
                <div className="tl-line" />
              </div>
              <div className="tl-right">
                <div className="tl-header">
                  <span className="tl-type-label">{label}</span>
                  <span style={{ display: "flex", alignItems: "center", gap: 0 }}>
                    <span className="tl-date-label">{formatShortDate(e.date)}</span>
                    <button
                      className="tl-delete"
                      type="button"
                      onClick={() => deleteTimelineEntry(e.id)}
                      aria-label="Delete entry"
                    >
                      &times;
                    </button>
                  </span>
                </div>
                {e.note ? (
                  <div
                    className="tl-note-text"
                    dangerouslySetInnerHTML={{ __html: escHtml(e.note) }}
                  />
                ) : null}
              </div>
            </div>
          );
        })}
      </div>

      {entries.length === 0 ? (
        <div id="tl-empty" style={{ textAlign: "center", padding: "3rem 1rem", color: "var(--text-3)" }}>
          <svg
            viewBox="0 0 24 24"
            width="40"
            height="40"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.2"
            strokeLinecap="round"
            strokeLinejoin="round"
            style={{ margin: "0 auto 12px", display: "block", opacity: 0.35 }}
          >
            <circle cx="12" cy="12" r="10" />
            <polyline points="12 6 12 12 16 14" />
          </svg>
          <div style={{ fontSize: 14, fontWeight: 500, marginBottom: 6 }}>No events logged yet</div>
          <div style={{ fontSize: 13 }}>
            Add your first entry above — start with the date you first noticed the problem.
          </div>
        </div>
      ) : (
        <div id="tl-empty" style={{ display: "none" }} />
      )}
    </>
  );
}
