"use client";

import { useState } from "react";
import { PRO_SCREENS, VLT_KEY, VLT_TYPE_LABELS } from "@/lib/data/constants";
import { useLocalStorage } from "@/lib/hooks/useLocalStorage";
import { useApp } from "@/lib/context/AppProvider";
import { formatLongDate, formatMediumDate } from "@/lib/utils";
import type { VaultEntry } from "@/types";

export function VaultView() {
  const { isPro, openPaywall, showToast } = useApp();
  const [entries, setEntries] = useLocalStorage<VaultEntry[]>(VLT_KEY, []);
  const [date, setDate] = useState("");
  const [type, setType] = useState("photo");
  const [title, setTitle] = useState("");
  const [note, setNote] = useState("");

  const sorted = [...entries].sort((a, b) => (a.date < b.date ? -1 : 1));

  const addVaultEntry = () => {
    if (!isPro) {
      openPaywall("Document vault — Pro only", PRO_SCREENS.vault);
      return;
    }
    if (!date) {
      showToast("Please select a date.");
      return;
    }
    if (!title.trim()) {
      showToast("Please add a document name.");
      return;
    }
    setEntries((prev) => [
      ...prev,
      { id: Date.now(), date, type, title: title.trim(), note: note.trim() },
    ]);
    setTitle("");
    setNote("");
    setDate("");
    showToast("Document added to vault.");
  };

  const deleteVaultEntry = (id: number) => {
    setEntries((prev) => prev.filter((e) => e.id !== id));
    showToast("Entry removed.");
  };

  const exportVault = () => {
    if (!entries.length) {
      showToast("No documents to export.");
      return;
    }
    let out = "RENTER RIGHTS AI — DOCUMENT VAULT\n";
    out +=
      "Exported: " +
      new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      }) +
      "\n";
    out += "─".repeat(48) + "\n\n";
    sorted.forEach((e) => {
      const label = VLT_TYPE_LABELS[e.type as keyof typeof VLT_TYPE_LABELS] || e.type;
      out += formatLongDate(e.date) + "\n";
      out += "[" + label + "] " + e.title + "\n";
      if (e.note) out += e.note + "\n";
      out += "\n";
    });
    out += "─".repeat(48) + "\nGenerated by renterrightsai.com";
    navigator.clipboard
      .writeText(out)
      .then(() => showToast("Vault copied to clipboard."))
      .catch(() => showToast("Copy failed — try again."));
  };

  const clearVault = () => {
    if (!confirm("Delete all vault entries? This cannot be undone.")) return;
    setEntries([]);
    showToast("Vault cleared.");
  };

  return (
    <>
      <div className="page-header">
        <div className="page-eyebrow">Document vault</div>
        <h1 className="page-title">Your evidence file</h1>
        <p className="page-sub">
          Store notes, links, and descriptions of photos, emails, and receipts related to your dispute.
          Build a complete evidence record in one place.
        </p>
      </div>
      <div className="callout callout-blue">
        <svg viewBox="0 0 24 24">
          <circle cx="12" cy="12" r="10" />
          <line x1="12" y1="8" x2="12" y2="12" />
          <line x1="12" y1="16" x2="12.01" y2="16" />
        </svg>
        <div>
          Add a note for each piece of evidence you have — photos, texts, emails, receipts. Use Export to
          copy your full vault as plain text to save or email to yourself.
        </div>
      </div>

      <div className="card" style={{ marginBottom: "1.5rem" }}>
        <div className="card-title">
          <svg
            viewBox="0 0 24 24"
            width="16"
            height="16"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
            <polyline points="14 2 14 8 20 8" />
          </svg>
          Add a document
        </div>
        <div className="form-grid" style={{ marginBottom: 10 }}>
          <div className="form-group" style={{ marginBottom: 0 }}>
            <label className="form-label" htmlFor="vlt-date">
              Date of document
            </label>
            <input
              className="form-input"
              id="vlt-date"
              type="date"
              value={date}
              onChange={(e) => setDate(e.target.value)}
            />
          </div>
          <div className="form-group" style={{ marginBottom: 0 }}>
            <label className="form-label" htmlFor="vlt-type">
              Document type
            </label>
            <select
              className="form-input"
              id="vlt-type"
              value={type}
              onChange={(e) => setType(e.target.value)}
            >
              <option value="photo">Photo / video</option>
              <option value="email">Email or text message</option>
              <option value="letter">Letter or notice</option>
              <option value="receipt">Receipt or invoice</option>
              <option value="report">Inspection or repair report</option>
              <option value="lease">Lease agreement / addendum</option>
              <option value="other">Other</option>
            </select>
          </div>
        </div>
        <div className="form-group">
          <label className="form-label" htmlFor="vlt-title">
            Document name or description
          </label>
          <input
            className="form-input"
            id="vlt-title"
            type="text"
            placeholder="e.g. Photo of mold on bathroom ceiling — taken Nov 4"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
        </div>
        <div className="form-group">
          <label className="form-label" htmlFor="vlt-note">
            Additional notes{" "}
            <span
              style={{
                fontWeight: 400,
                textTransform: "none",
                letterSpacing: 0,
                color: "var(--text-3)",
              }}
            >
              (optional)
            </span>
          </label>
          <textarea
            className="form-input"
            id="vlt-note"
            rows={2}
            placeholder="e.g. Shows visible mold spreading from grout line. Timestamp visible in corner. Sent to landlord via email same day."
            style={{ resize: "vertical" }}
            value={note}
            onChange={(e) => setNote(e.target.value)}
          />
        </div>
        <div className="btn-row" style={{ marginTop: 0 }}>
          <button className="btn btn-primary" type="button" onClick={addVaultEntry}>
            Add to vault
          </button>
        </div>
      </div>

      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 10,
          flexWrap: "wrap",
          gap: 8,
        }}
      >
        <div className="sec-label" style={{ marginBottom: 0 }} id="vlt-count">
          {entries.length === 0
            ? "No documents yet"
            : `${entries.length} document${entries.length === 1 ? "" : "s"} stored`}
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          <button className="btn btn-sm" type="button" onClick={exportVault}>
            Export
          </button>
          <button
            className="btn btn-sm"
            type="button"
            onClick={clearVault}
            style={{ color: "var(--red)" }}
          >
            Clear all
          </button>
        </div>
      </div>

      <div id="vlt-entries">
        {sorted.map((e) => {
          const label = VLT_TYPE_LABELS[e.type as keyof typeof VLT_TYPE_LABELS] || e.type;
          return (
            <div className="card card-sm" style={{ marginBottom: 8 }} key={e.id}>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "flex-start",
                  gap: 8,
                  flexWrap: "wrap",
                }}
              >
                <div style={{ flex: 1 }}>
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: 8,
                      marginBottom: 4,
                      flexWrap: "wrap",
                    }}
                  >
                    <span style={{ fontSize: 13, fontWeight: 600, color: "var(--text)" }}>
                      {e.title}
                    </span>
                    <span className="pill pill-blue">{label}</span>
                  </div>
                  <div
                    style={{
                      fontSize: 12,
                      color: "var(--text-3)",
                      marginBottom: e.note ? 6 : 0,
                    }}
                  >
                    {formatMediumDate(e.date)}
                  </div>
                  {e.note ? (
                    <div style={{ fontSize: 13, color: "var(--text-2)", lineHeight: 1.6 }}>
                      {e.note}
                    </div>
                  ) : null}
                </div>
                <button
                  type="button"
                  onClick={() => deleteVaultEntry(e.id)}
                  style={{
                    background: "none",
                    border: "none",
                    cursor: "pointer",
                    color: "var(--text-3)",
                    fontSize: 18,
                    padding: 0,
                    flexShrink: 0,
                  }}
                  aria-label="Delete"
                >
                  &times;
                </button>
              </div>
            </div>
          );
        })}
      </div>

      {entries.length === 0 ? (
        <div id="vlt-empty" style={{ textAlign: "center", padding: "3rem 1rem", color: "var(--text-3)" }}>
          <svg
            viewBox="0 0 24 24"
            width="40"
            height="40"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.2"
            strokeLinecap="round"
            strokeLinejoin="round"
            style={{ margin: "0 auto 12px", display: "block", opacity: 0.35 }}
          >
            <path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z" />
          </svg>
          <div style={{ fontSize: 14, fontWeight: 500, marginBottom: 6 }}>No documents logged yet</div>
          <div style={{ fontSize: 13 }}>
            Add your first entry above — photos, emails, and receipts are your strongest evidence.
          </div>
        </div>
      ) : (
        <div id="vlt-empty" style={{ display: "none" }} />
      )}
    </>
  );
}
